### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ImagicalGamer** [TransendStudios/Trinket#1]
- [x] Better Error Handle

- [ ] Add More Packets (and packet uses DUH)

- [x] Better Client Management

**Comment by RedstoneAlmeida** [comment]
hey, it's possible create Trinket in PHP Version, If possible, I can help you make a very wide version.

**Comment by ImagicalGamer** [comment]
I chose python for a reason :). I like the multi-threading better than PHP or Java, PHP was intended for websites not a software so not using PHP. I will probs port to Java once it's done, I'll let you know when and you're welcome to help :)

**Comment by RedstoneAlmeida** [comment]
Thanks a lot for letting me help too, the idea is very good, I already see several things in my mind to use this, I will learn a little more of python, to be able to make it very practical, I am still kind of noob, so I asked to carry For php or java, lmao

**Comment by ImagicalGamer** [comment]
Awesome, I need more ideas for it. Currently the plugin is more of a developer tools for multi-server communication.

**Comment by ImagicalGamer** [comment]
@RedstoneAlmeida Im not sure but I want to integrate Trinket into the plugin, but I'm not sure how that would affect PMMP's performance.

**Comment by RedstoneAlmeida** [comment]
I think it would be nice to leave in a way software from outside an API, because I think it would be easier, in the case of Nemisys with Synapse, which is very similar to Trinket

**Comment by RedstoneAlmeida** [comment]
One of my ideas is to use the communication system, to get server MOTD, Slots, list of online players, Server situation (whitelisted or server off), between some things using JSON to transfer information, like this: {players: 30 , Motd: "server is online"}

**Comment by ImagicalGamer** [comment]
Same, I tried doing a server and client on the plugin but data got mixed up and it was too difficult to manage.

**Comment by ImagicalGamer** [comment]
I fixed packet receiving client side so everything should be semi easy now (command and chat packets)

**Comment by ImagicalGamer** [comment]
I'll work on a packet for that, hardest thing atm is caching what was sent client side so if the client sends a packet requesting data and then receives a packet with the data 30 packets later when it should be the first packet it isnt entirely ignored. I may store that info in the 'DummyPacket' so it can update client side every second.

**Comment by RedstoneAlmeida** [comment]
Package with chat between servers would be nice, and if possible in TrinketPM set an event to disable in certain worlds, type ... LinkedChatEvent

**Comment by RedstoneAlmeida** [comment]
DummyPacket work similar to Ticks?

**Comment by ImagicalGamer** [comment]
Yes, DummyPacket's are used to keep the connection alive (even though there is no timeout). Whenever the client logs into the server a login packet is sent back to the client (to let them know they were authenticated) and then a dummy packet. When the client receives a dummy packet they send one, whenever the server receives a dummy packet it sends one. It's like a recursive function only with sockets.

**Comment by RedstoneAlmeida** [comment]
Type, when server receives a dummy it sends the player a dummy back, right? Is this meant to maintain a stable connection, and the player or client does not disconnect from anything?

**Comment by ImagicalGamer** [comment]
Yes, it is meant to maintain a stable connection between the plugin and remote server. We could have the plug process dummypackets and cache data like player counts, player list etc from all servers connected to the trinket server.

**Comment by RedstoneAlmeida** [comment]
Is a good idea, I think it would be to use in a json packet, to make it easier to manipulate an array with the contents of the connected players in general or servers connected in the trinket, all in a single packet, that will come without loss because it is TCP

**Comment by ImagicalGamer** [comment]
The packets are JSON and utf-8 encoded (I think) Python won't send a raw JSON encoded string but it does the utf-8 encoded one and PHP processes the UTF encoding like JSON so there's no conflict.

**Comment by RedstoneAlmeida** [comment]
Could come in a decoded, something like server status, slots and busy slots, I think, we'll have to see it right still, it seems we already have a base

**Comment by ImagicalGamer** [comment]
@RedstoneAlmeida look at [https://github.com/TransendStudios/TrinketPM/commit/517583ed6622381c4fdcee1749a18e40a8f928b4](https://github.com/TransendStudios/TrinketPM/commit/517583ed6622381c4fdcee1749a18e40a8f928b4), I added a queue for commands sent from trinket to trinketpm plugin. I had to extend the \Threaded class so PacketReadTask class can push objects but whenever the PluginTask that executes commands checks the queue it returns empty. It shows as empty to non threaded tasks.

**Comment by RedstoneAlmeida** [comment]
It works type runs the command "/ say hello players" eg it runs on the trinket then sends it to TrinketPM, and so runs inside the server?

**Comment by RedstoneAlmeida** [comment]
@ImagicalGamer It works type runs the command "/ say hello players" eg it runs on the trinket then sends it to TrinketPM, and so runs inside the server?

**Comment by ImagicalGamer** [comment]
The command packet (not on github yet) allows for servers to send a command to the trinket server with a serverID, if the serverID is connected to trinket it sends the command to that server. I even tried locally (within the plug) pushing commands to the queue and it still returns an empty array.

**Comment by RedstoneAlmeida** [comment]
Has already tried something like get the message of the command type, "say hello guys" and then use a ConsoleCommandSender in dispatch?

**Comment by ImagicalGamer** [comment]
The packets are received on a new thread so I cant dispatch commands thats why I had a queue and the main thread has a task that dispatches them.

**Comment by RedstoneAlmeida** [comment]
I understand, but it still returns an empty queue .. it may be that the thread has been restarted ahead of time.

**Comment by ImagicalGamer** [comment]
Might have a fix...

**Comment by RedstoneAlmeida** [comment]
Has to have a correction, not impossible, I still think it may be a mistake at some point in Trinket, which sends without something. Maybe missing characters

**Comment by ImagicalGamer** [comment]
It's client side queue issue, I just fixed it. About to push to TrinketPM repo.

**Comment by RedstoneAlmeida** [comment]
It may be entering empty, inside the thread at the time of running with the client, or for lack of a foreach ...

**Comment by ImagicalGamer** [comment]
It was a simple fix, when a new thread called the queue from another thread it reset the queue to be empty.

**Comment by RedstoneAlmeida** [comment]
I knew that maybe it would be a redefinition of the queue, I had several problems with that already, lmao

**Comment by ImagicalGamer** [comment]
Make a new branch for any more util commits, and dont make any packet commits Im rewriting the packet system rn.

**Comment by ImagicalGamer** [comment]
Pushed my last few commits to the wrong branch so I went ahead and merged packets branch into master branch. Commits aren't in order lol

**Comment by RedstoneAlmeida** [comment]
lol

**Comment by ImagicalGamer** [comment]
CommandPacket and ChatPacket both work, I'm still working on directing the command to the specified server.

**Comment by ImagicalGamer** [comment]
Trying to setup circleci correctly. 😃

**Comment by RedstoneAlmeida** [comment]
oh, good 😃
